# Generated by Django 3.2.9 on 2021-11-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdeatils',
            name='ISBN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookdeatils',
            name='language',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
