# Generated by Django 3.2.9 on 2021-11-20 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211120_0654'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDeatils',
            new_name='BookDetails',
        ),
    ]
