# Generated by Django 3.2.9 on 2021-11-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_bookdeatils_bookdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
