# Generated by Django 3.2.9 on 2021-11-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bookdetails_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookdetails',
            old_name='autor_id',
            new_name='author_id',
        ),
    ]
